"""Seed clearly-labeled DEMO data so the dashboard renders without an
OpenRouter key.

Uses the existing price cache (real Yahoo data when available, synthetic
otherwise) and creates 12 monthly demo runs whose verdicts come from a
deterministic momentum heuristic (NOT real LLM output — every run is
kind="demo" and the model name says so).

CLI: python -m backend.stocks.seed_demo
"""

from datetime import datetime, timezone

from . import store
from .backfill import historical_run_dates
from .config import TICKERS, PRICES_CACHE_CSV
from .council_runner import normalize_verdicts
from .data import (
    build_snapshot,
    generate_synthetic_prices,
    load_cached_prices,
    save_prices_cache,
)

DEMO_MODEL = "demo/synthetic-heuristic"


def _heuristic_verdicts(prices, as_of):
    """Deterministic 3-month momentum rule, just to populate the UI."""
    raw = []
    for ticker in TICKERS:
        snap = build_snapshot(ticker, as_of, prices)
        r3m = snap.get("return_3m_pct") or 0
        if r3m > 5:
            stance, weight = "LONG", min(0.20, 0.05 + r3m / 200)
        elif r3m < -5:
            stance, weight = "SHORT", -min(0.15, 0.05 + abs(r3m) / 250)
        else:
            stance, weight = "FLAT", 0.0
        raw.append({
            "ticker": ticker,
            "stance": stance,
            "conviction": 5,
            "target_weight": weight,
            "rationale": f"DEMO momentum rule (not LLM output): 3-month return {r3m:+.1f}%.",
        })
    return raw


def seed(months: int = 12) -> None:
    prices = load_cached_prices()
    if prices is None:
        prices = generate_synthetic_prices()
        save_prices_cache(prices, source="synthetic-demo")
        print(f"Wrote synthetic price cache to {PRICES_CACHE_CSV}")

    memo = (
        "DEMO DATA — generated by a momentum heuristic on synthetic prices, "
        "not by LLM deliberation. Run the real backfill to replace it."
    )
    for d in historical_run_dates(prices, months):
        run_id = f"demo-{d}"
        if store.load_run(run_id):
            continue
        verdicts, target = normalize_verdicts(_heuristic_verdicts(prices, d), TICKERS)
        from .schemas import CouncilRun
        run = CouncilRun(
            run_id=run_id,
            kind="demo",
            as_of=str(d),
            created_at=datetime.now(timezone.utc).isoformat(),
            status="complete",
            progress={"stage": "done"},
            models={"analysts": [DEMO_MODEL], "chairman": DEMO_MODEL},
            tickers=TICKERS,
            stage1=[{"model": DEMO_MODEL, "response": memo}],
            stage3={"model": DEMO_MODEL, "response": memo},
            verdicts=verdicts,
            portfolio_target=target,
        )
        store.save_run(run)
        print(f"Seeded {run_id}")


if __name__ == "__main__":
    seed()
